---
title: "빅콘테스트_R코드"
author: "베리스트롱"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

## **1. 분석 준비**

###  **1.1 라이브러리 임포트**
```{r}
library(VariableScreening)
library(glmnet)
library(MFSIS)
# set.seed 설정
set.seed(1)
```

### **1.2 데이터 로드**
- 파이썬 상에서 내보낸 stadardizing 시킨 파일명으로 불러오기
```{r}
data = read.csv('C:/Users/kyeongmoo/Downloads/strawberry_increase_scaled.csv')
```

### **1.3 변수 설정**
```{r}
X=data[,3:30]   # date와 DIFF컬럼 제거
Y=data$DIFF     # DIFF 변수만 저장
```

---

## **2. Screening 실행 코드**

### **2.1 VariableScreening 패키지의 screenIID 함수** 
```{r}
result_screeniid <- screenIID(X, Y, method = "SIRS")
(screendIID_12 <- sort(result_screeniid$measurement[result_screeniid$rank<13], decreasing=TRUE) )
x_screeniid <- names(screendIID_12)  

screeniid_lm <- lm(DIFF ~ ., data = data[, c(x_screeniid, 'DIFF')])
summary(screeniid_lm); 

AIC(screeniid_lm)

# 회귀 계수와 p-value만 추출하여 데이터프레임으로 변환
coef_screeniid_lm <- summary(screeniid_lm)$coefficients[, c("Estimate", "Pr(>|t|)")]
coef_screeniid_lm <- as.data.frame(coef_screeniid_lm)
colnames(coef_screeniid_lm) <- c("Coefficient", "P_Value")

# 결과 출력
print(coef_screeniid_lm)
```

### **2.2 MFSIS패키지의 CSIS 함수** 
```{r}
result_CSIS = CSIS(X, Y, nsis=12)
(CSIS_12 = colnames(X)[result_CSIS])

CSIS_lm <- lm(Y~., data=cbind(data[,CSIS_12],Y))
summary(CSIS_lm)

AIC(CSIS_lm)

# 회귀 계수와 p-value만 추출하여 데이터프레임으로 변환
coef_CSIS_lm <- summary(CSIS_lm)$coefficients[, c("Estimate", "Pr(>|t|)")]
coef_CSIS_lm <- as.data.frame(coef_CSIS_lm)
colnames(coef_CSIS_lm) <- c("Coefficient", "P_Value")

# 결과 출력
print(coef_CSIS_lm)
```

---

## **3. LASSO 실행 코드**
```{r}
# 변수 설정
X <- as.matrix(data[, c(3:30)])
Y <- as.vector(data$DIFF)
lasso_model <- glmnet(X, Y, alpha = 1)  # alpha = 1은 Lasso 회귀를 나타낸다.

# 교차 검증을 통한 최적 lambda 선택 
cv_lasso_model <- cv.glmnet(X, Y, alpha = 1)
best_lambda <- cv_lasso_model$lambda.min
best_lambda
```

```{r}
# 최적 lambda 값에 대한 Lasso 모델 적합
lasso_model_best_lambda <- glmnet(X, Y, alpha = 1, lambda = best_lambda)

# coef에서 0이 아닌 값과 해당 변수명 추출
nonzero_coef_indices <- which(coef(lasso_model_best_lambda) != 0, arr.ind = TRUE)
nonzero_coefs <- coef(lasso_model_best_lambda)[nonzero_coef_indices]
column_names <- rownames(coef(lasso_model_best_lambda))[nonzero_coef_indices[, "row"]]

# 결과 출력
result_df <- data.frame(Coefficient = nonzero_coefs, Column_Name = column_names)
print(result_df)
```
